name: day_record
description: "每日成長與開發實踐紀錄"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  googleapis: ^16.0.0
  google_sign_in: ^7.2.0
  extension_google_sign_in_as_googleapis_auth: ^3.0.0
  provider: ^6.1.2
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
